#!/usr/bin/env python3
"""Generate the memory_regions.ld that script/fsp.ld INCLUDEs.

e2 studio normally emits this file as part of its RA content generation step,
which is why it is not checked in. When building from the command line we
regenerate it from the same source of truth the configurator uses: the
<memories> block of the project's .rzone description, which carries the base
address and size of every memory for the configured part number.

Usage: gen_memory_regions.py <input .secure_rzone> <output memory_regions.ld>
"""

import sys
import xml.etree.ElementTree as ET

# Memories fsp.ld expects, in the order it is easiest to read them back.
EXPECTED = [
    "RAM",
    "FLASH",
    "DATA_FLASH",
    "OPTION_SETTING",
    "OPTION_SETTING_S",
    "ID_CODE",
    "SDRAM",
    "QSPI_FLASH",
    "OSPI_DEVICE_0",
    "OSPI_DEVICE_1",
]


def main(rzone_path, out_path):
    root = ET.parse(rzone_path).getroot()
    memories = {
        m.get("name"): (int(m.get("start"), 16), int(m.get("size"), 16))
        for m in root.iter("memory")
    }

    missing = [name for name in EXPECTED if name not in memories]
    if missing:
        sys.exit(f"{rzone_path}: no <memory> entry for {', '.join(missing)}")

    lines = [
        "/* Generated by script/gen_memory_regions.py from the project .rzone -- do not edit. */",
    ]
    for name in EXPECTED:
        start, size = memories[name]
        lines.append(f"{name}_START = 0x{start:08X};")
        lines.append(f"{name}_LENGTH = 0x{size:X};")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
