/***********************************************************************************************************************
 * hal_entry.c - FSP boilerplate. Almost nothing of this project lives here.
 *
 * This build uses FreeRTOS, so the generated main() starts the scheduler and the
 * real work happens in the tasks declared in ra_gen/: dap_thread_entry() (see
 * dap_thread_entry.c) and swo_thread_entry() (swo_thread_entry.c). hal_entry()
 * below is the no-RTOS path and is never called.
 *
 * The one thing here that matters is R_BSP_WarmStart(), which runs before main()
 * and applies the pin configuration - including the SWD, nRESET, SWO, VCOM and
 * status-LED pins that the rest of the firmware then drives directly through port
 * registers.
 *
 * Regenerated by the e2 studio RA Configuration editor. Keep edits minimal.
 **********************************************************************************************************************/

#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 *
 * NOT CALLED in this project - FreeRTOS is enabled, so the generated main() hands
 * control to the scheduler instead. Left empty and in place for FSP parity.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins.
         *
         * This is where every pin this firmware depends on gets its mode, from
         * g_bsp_pin_cfg in ra_gen/. It is the ONLY place they are configured -
         * nothing afterwards touches PFS.
         *
         * That matters for the SWD path in particular. CMSIS-DAP/DAP_config.h
         * drives SWDIO (P101), SWCLK (P102) and nRESET (P112) through raw PCNTR
         * register writes for speed, which assumes those pins are already GPIO
         * with PMR = 0 - established here and never re-established. Likewise the
         * status LED on P111, SCI0 RXD on P100 for SWO, and SCI2 on P302/P301 for
         * VCOM. Anything that reconfigured these at runtime would have to put them
         * back itself. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
